### ISSUE TITLE
Payment Gateway not working

### ISSUE THREAD

**Issue by MuthuvelA** [MAVRICK-1/Nest-Ondc#1]
**Describe the bug**
The Checkout button in cart does not work and it is not redirecting to the payment methods

**To Reproduce**
add some products and proceed with checkout but it stays in same page

**Expected behavior**
Should be redirected secure payment gateway

**Screenshots**
![image](https://github.com/MAVRICK-1/Nest-Ondc/assets/125255596/c98479ea-00d3-4041-b7b9-ef049c5ab0f8)

**Desktop (please complete the following information):**

**Additional context**
I have read the contributing guidelines and code of conduct. I have prior experience working in open source projects so @MAVRICK-1 please assign this issue to me under label ssoc'24 level 3. Thank You

**Comment by MAVRICK-1** [comment]
@MuthuvelA Payment gateway is not integrate yet , tell me how you gonna handle it

**Comment by MuthuvelA** [comment]
@MAVRICK-1  **Integrating Razorpay Payment Gateway in React Application**

1. The integration of the Razorpay payment gateway will be achieved by dynamically loading the Razorpay checkout script using a custom React component.
2. A new component will be created to handle the payment process. This component will include:
3. A form to capture the payment amount.
4. A button to initiate the payment process.
5. Upon form submission, the component will:
6. Validate the input amount.

- Configure the Razorpay checkout with necessary options such as key ID, amount (in paise), currency, and user details.
- Use the Razorpay JavaScript SDK to open the checkout modal and process the payment.
- Successful payments will return a payment ID, which will be handled appropriately.
- Error handling mechanisms will be implemented to manage scenarios where the Razorpay script fails to load or the payment process encounters issues, ensuring a smooth user experience.

Please assign this issue to me under level 3 with ssoc tag

**Comment by MAVRICK-1** [comment]
@MuthuvelA tags will be discussed  today , then will add the label
