### ISSUE TITLE
Payment Gateway integration & Other Minor fixes

### ISSUE THREAD

**Issue by dfordp** [MAVRICK-1/Nest-Ondc#10]
**Is your feature request related to a problem? Please describe.**

- There is no payment gateway integrated into the application for handling the checkout as also mention in other issues

**Describe the solution you'd like**
Integrating Stripe Webhook into the application based in a foreign country cause of reason given below

**Describe alternatives you've considered**
We could use razorpay but it both stripe and razor pay require a a business id / license to use in India 

**Additional context**
![geg](https://github.com/MAVRICK-1/Nest-Ondc/assets/92905896/d57b51e7-f207-4027-b2f7-8090dcebc74c)

I would like to work on this issue

**Comment by MAVRICK-1** [comment]
@dfordp duplicate issue #1

**Comment by dfordp** [comment]
By that time the person had no been assigned the issues and that's why I raised the issue again. 

There was also and issue in the blog and contact page and the top bar of the webpage had an compare section which was leading to wishlist route and their didn't exist a route for the same

So the tasks at hand
- Fixing an email based service for handling customer grievances  
- Blog section allowing viewers to add various greviences and discuss amongst themselves  which are not that high priority or required to be fixed by a developer 

Can you assign me this issue?
