### ISSUE TITLE
Repetitive Product Listings in TRENDING PRODUCTS

### ISSUE THREAD

**Issue by sakshiglaze** [MAVRICK-1/Nest-Ondc#103]
Hello @MAVRICK-1 
**Describe the bug**
The repeated listing of the same item (Nestle Original Coffee-Mate Coffee Creamer) multiple times appears incomplete or inappropriate. This repetition could lead users to perceive the website as amateurish or to assume there is a technical issue causing the site to crash or malfunction.

**Expected behavior**
 To improve the user experience and professional appearance, I would recommend rewriting or restructuring this section to display each unique product listing only once.

**Screenshots**
![Screenshot 2024-06-12 032919](https://github.com/MAVRICK-1/Nest-Ondc/assets/129287425/7b94c655-e976-4b57-bc23-3bd9c08b9d2d)

Please share a glimpse or provide a list of the items you feel would appeal most to your customers and give them a sense of your popular product offerings. Your first-hand insight into the merchandise you wish to highlight would be greatly appreciated when organizing an effective and enticing product display.
Please assign this issue under SSOC'24
Thankyou!

**Comment by Sahilll15** [comment]
@sakshiglaze dont repeat the same issue
