### ISSUE TITLE
Ensuring a Unique, Well-Curated TOP RATED Product Showcase 

### ISSUE THREAD

**Issue by sakshiglaze** [MAVRICK-1/Nest-Ondc#105]
Hello @MAVRICK-1
**Describe the bug**
The repeated listing of the same item (Nestle Original Coffee-Mate Coffee Creamer) multiple times appears incomplete or inappropriate. This repetition could lead users to perceive the website as amateurish or to assume there is a technical issue causing the site to crash or malfunction.

**Expected behavior**
To improve the user experience and professional appearance, I would recommend rewriting or restructuring this section to display each unique product listing only once.

**Screenshots**
![Screenshot 2024-06-12 033523](https://github.com/MAVRICK-1/Nest-Ondc/assets/129287425/cd3c1d28-1156-41f5-8bf5-46714d94705f)

Please share a glimpse or provide a list of the items you feel would appeal most to your customers and give them a sense of your popular product offerings. Your first-hand insight into the merchandise you wish to highlight would be greatly appreciated when organizing an effective and enticing product display.
Please assign this issue under SSOC'24
Thankyou!

**Comment by Sahilll15** [comment]
@sakshiglaze u can work on this issue

**Comment by sakshiglaze** [comment]
Hello @Sahilll15 
I have incorporated some products according to my liking. If there is something you want to add do let me know. Here is a glimpse of what I have done. Kindly share your thoughts on the same after that I would ask for pull request.
![Screenshot 2024-06-18 011135](https://github.com/MAVRICK-1/Nest-Ondc/assets/129287425/c1097dd2-2e5e-4f55-9b7a-5f5a75ffc9ff)



Also it's a gently reminder to put gssoc24, ssoc24 and level label on the issue.
ThankYou!

**Comment by sakshiglaze** [comment]
Hello @MAVRICK-1 @Sahilll15 
I'll be highly obliged if you could add the labels of gssoc24 and ssoc24 and difficulty level. Since I'm contributing in both.
PR merged#110

Issue#105
ThankYou!

**Comment by MAVRICK-1** [comment]
@sakshiglaze it's registered for ssoc24 not gssoc

**Comment by MAVRICK-1** [comment]
Labels added
