### ISSUE TITLE
Feature🌟: Add "Terms and Conditions" and "Privacy Policy" Pages to Footer

### ISSUE THREAD

**Issue by aslams2020** [MAVRICK-1/Nest-Ondc#115]
Hey @MAVRICK-1 

i want to create and add two separate pages in the website's footer by adding links to two new pages: Terms and Conditions and Privacy Policy. 
These pages are essential for informing users about the legal aspects of using our site and ensuring compliance with privacy regulations.

**What will i do**
1.Create Terms and Conditions Page
 - Develop a new page titled "Terms and Conditions."
- Include comprehensive terms that cover the use of our website, user responsibilities, limitations of liability, and other relevant legal 

2. Create Privacy Policy Page
- Develop a new page titled "Privacy Policy."
- Detail how we collect, use, and protect user data.

3. Update Footer
- Add links to the newly created "Terms and Conditions" and "Privacy Policy" pages in the website's footer.

Could you Please assign me this issue under SSoC'24 ?

**Comment by kushagra-singhh** [comment]
TnC page has been added in https://github.com/MAVRICK-1/Nest-Ondc/pull/93
