### ISSUE TITLE
Feature 💡: Styling the Footer Section

### ISSUE THREAD

**Issue by aslams2020** [MAVRICK-1/Nest-Ondc#119]
Hey @akbatra567 , 
Here is the feature i want to suggest - 

I **want to style the Footer section** in the website,
The requested feature involves improving the styling and functionality of the footer section on a website
This includes ensuring responsive design, optimizing the layout for different screen sizes, and enhancing the visual appeal and usability of the footer.

Current footer section -

![image](https://github.com/MAVRICK-1/Nest-Ondc/assets/131389695/c535dee4-3cfa-4d58-81ea-ea6dfd8310b9)

The enhanced footer section styling will bring numerous benefits to the project, including improved user experience, increased accessibility, better user engagement, and a more professional appearance.
By implementing these changes, the project will offer a more polished and user-friendly interface, ultimately contributing to its success and user satisfaction.

@akbatra567, Could you please assign me this issue under SSoC'24 ?
Thankyou!

**Comment by akbatra567** [comment]
@aslams2020, could you share more details on what all you are hoping to add or fix. We can discuss the scope for this. 
So it's easier to implement for you and easier to review as well.
