### ISSUE TITLE
Adding Jump to top arrow button in footer section

### ISSUE THREAD

**Issue by harinisayani** [MAVRICK-1/Nest-Ondc#13]
**Is your feature request related to a problem? Please describe.**
Jump to top arrow button in footer section is not available in footer section.

**Describe the solution you'd like**
I want to add jump to top arrow button in footer section.

**Additional context**
I am SSOC'24 contributor.
Please assign me this issue.

**Comment by MAVRICK-1** [comment]
@harinisayani okay go ahead

**Comment by akbatra567** [comment]
PR merged: https://github.com/MAVRICK-1/Nest-Ondc/pull/90
