### ISSUE TITLE
Changing twitter logo

### ISSUE THREAD

**Issue by harikasayani** [MAVRICK-1/Nest-Ondc#14]
**Describe the bug**
I observed that there is incorrect icon for twitter.

**To Reproduce**
I'll change the icon and add correct icon.

**Screenshots**
![Uploading Screenshot (145).png…]()

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
I am SSOC'24 Contributor.
Please assign me this task.
I want to work on this issue.

**Comment by MAVRICK-1** [comment]
@harikasayani okay go ahead
