### ISSUE TITLE
Feature Request: Add Responsiveness to the Application

### ISSUE THREAD

**Issue by Ark2044** [MAVRICK-1/Nest-Ondc#18]
The current application layout is not fully responsive. When viewed on different devices such as tablets and mobile phones, the UI elements do not adapt well, causing a poor user experience. Elements might overlap, be cut off, or require excessive scrolling.

Implement responsive design principles across the application to ensure a seamless user experience on all device sizes. This could include:
**Media Queries**: Use CSS media queries to apply different styles based on the device screen size.
**Flexible Grid Layouts**: Utilize CSS grid or flexbox layouts to create flexible and adaptive layouts.
**Responsive Images**: Ensure images are scalable and adjust based on the screen size.
**Hamburger Menu**: Implement a hamburger button that reveals a collapsible navigation menu on smaller screens.
**Testing on Various Devices**: Test the application on various devices and screen sizes to ensure consistency.

**Comment by Ark2044** [comment]
Please assign this issue to me.

**Comment by MAVRICK-1** [comment]
@Ark2044 everything is already implemented
