### ISSUE TITLE
Duplicate entry in Footer section

### ISSUE THREAD

**Issue by adarsh-site** [MAVRICK-1/Nest-Ondc#19]
**Describe the bug**
There are some duplicate entries in the footer section.

**To Reproduce**
Remove unnecessary entries from the footer section

**Expected behavior**
A clear and concise footer section with repetation entries.

**Screenshots**
![image](https://github.com/MAVRICK-1/Nest-Ondc/assets/120160355/cca26512-e3c5-4531-aca5-8ddf0717eaac)

**Desktop (please complete the following information):**

- OS: windows
- Browser chrome

**Additional context**

**Comment by adarsh-site** [comment]
hey @MAVRICK-1 please assign this issue to me.

**Comment by MAVRICK-1** [comment]
@jinx-vi-0 okay go ahead
