### ISSUE TITLE
LIGHT/DARK MODE BUTTON &SCROLLDOWN BUTTON 

### ISSUE THREAD

**Issue by Soumyacode1-prog** [MAVRICK-1/Nest-Ondc#2]
Dark mode can reduce eye strain, especially in low-light environments, making it more comfortable for users to read content for extended periods.
Different users have different visual preferences and needs. Providing both light and dark modes ensures that the interface is accessible to a broader audience, including those with visual impairments or light sensitivity.
A scroll-down button (often represented as a downward arrow) can significantly improve the user experience on web pages and applications
PLEASE ALLOW ME TO MAKE THESE CHANGES.

**Comment by MAVRICK-1** [comment]
@Soumyacode1-prog okay go ahead

**Comment by Soumyacode1-prog** [comment]
Thankyou! I am currently working on it and will complete it soon.

**Comment by Soumyacode1-prog** [comment]
Is this work completed by somebody else? Actually I have completed the work so if it is already done then i'll not push the code.
