### ISSUE TITLE
Replace $ Symbol with ₹ Symbol for INR

### ISSUE THREAD

**Issue by kushagra-singhh** [MAVRICK-1/Nest-Ondc#20]
# Description : 
I noticed that there are several instances where the $ (dollar) symbol is used throughout the marketplace. Since this is an Indian marketplace, it would be more appropriate to use the ₹ (Indian Rupee) symbol to represent prices in INR.

## Instances of $ Symbol : 
Here are a few places where the $ symbol appears:

- Home Page - Top Selling / Trendind Products / Recently Added / Top Rated

- All Products - Change 'Rs' with '₹'

## Suggested Change
Replace all instances of the $ symbol with the ₹ symbol to better reflect the local currency.

## Screenshots
![image](https://github.com/MAVRICK-1/Nest-Ondc/assets/88451512/2a381ff3-8c2b-4d1a-8936-39c18cbc16bb)
![image](https://github.com/MAVRICK-1/Nest-Ondc/assets/88451512/4912e5a0-a677-4db8-b872-1718c87bbe1b)

**Comment by kushagra-singhh** [comment]
@MAVRICK-1 I would like to take up this issue. Please assign it to me.

**Comment by MAVRICK-1** [comment]
@kushagra-singhh okay go ahead

**Comment by AsifpMulla123** [comment]
Admin please check my merge request

**Comment by AsifpMulla123** [comment]
> @MAVRICK-1 I would like to take up this issue. Please assign it to me.

Sorry but I was solved when it is open

**Comment by kushagra-singhh** [comment]
> > @MAVRICK-1 I would like to take up this issue. Please assign it to me.
> 
> Sorry but I was solved when it is open

If an issue has already been assigned then creating a pr without getting it assigned is not a good practice.

**Comment by AsifpMulla123** [comment]
Sorry

**Comment by MAVRICK-1** [comment]
@AsifpMulla123 it has been assigned to @kushagra-singhh  . Sry @AsifpMulla123 I can't accept your PR
