### ISSUE TITLE
Unresponsive news letter banner

### ISSUE THREAD

**Issue by iSubhamMani** [MAVRICK-1/Nest-Ondc#21]
**Describe the bug**
The news letter banner in the home screen is unresponsive on smaller devices

**To Reproduce**
Go to home page

**Screenshots**
![Screenshot from 2024-06-02 13-56-53](https://github.com/MAVRICK-1/Nest-Ondc/assets/134488182/5e1cfda5-cd3e-44ce-8abc-2578f6de204a)

**Comment by iSubhamMani** [comment]
Hey @MAVRICK-1 I would like to work on this issue under SSOC

**Comment by MAVRICK-1** [comment]
@iSubhamMani duplicate issue #11
