### ISSUE TITLE
Add more features on the landing page

### ISSUE THREAD

**Issue by nisargaa20** [MAVRICK-1/Nest-Ondc#23]
Kindly assign me under #SSOC

**Comment by BhumikaRahwani** [comment]
Is your feature request related to a problem? Please describe.
I observed that landing page is not looking good.

Describe the solution you'd like
I'll make it attractive by using icons and more CSS features.

Additional context
I am SSOC'24 Contributor.
Please assign me this task @MAVRICK-1 .
I want to work on this issue.

**Comment by MAVRICK-1** [comment]
@nisargaa20 okay go ahead , will mark you after seeing your PR
