### ISSUE TITLE
the card size are not-uniform and it could be unifrom throughout the page

### ISSUE THREAD

**Issue by tusharshah21** [MAVRICK-1/Nest-Ondc#24]
**Describe the bug**
the card's size is not same for every product which do not look attractive, even we could add a bit of shadows to the background of the card as the white color is same throughout the page

**To Reproduce**
1) make a fixed size for all the cards throughout the page
2) add some shadow to cards so it might look a bit seperate from the rest

**Screenshots**

![image](https://github.com/MAVRICK-1/Nest-Ondc/assets/96661387/3171c16a-ffb6-45ac-a714-5e663bc12a58)

I would like to fix it! If you agree, please do assign it to me under ssoc

**Comment by ArpanenduKhag** [comment]
Can I get assigned for this issue?

**Comment by tusharshah21** [comment]
@MAVRICK-1 can you look into this?

**Comment by MAVRICK-1** [comment]
@tusharshah21  okay go ahead
