### ISSUE TITLE
Fix & Update the Getting Started README

### ISSUE THREAD

**Issue by ShubhamTiwary914** [MAVRICK-1/Nest-Ondc#29]
**Describe the bug**
Updating the README.md Getting Started to run the Nest ONDC repo, instead of the ecommerce repo

**Expected behavior**
I want the Getting Started Section in the main README to:
- Indicate proper running specifications for the current repo,
- Including all the additional dependencies required for setting up

<br />

**Screenshots**
![Screenshot from 2024-06-02 20-27-20](https://github.com/MAVRICK-1/Nest-Ondc/assets/67773966/322b040c-8b06-4351-9fbc-a01c6111c29a)

**Additional Context**
- Contributing as an SSOC participant
- I'd like to be assigned on the specified issue.

**Comment by MAVRICK-1** [comment]
@ShubhamTiwary914 duplicate issue #6
