### ISSUE TITLE
Removal of duplicate Cards

### ISSUE THREAD

**Issue by phoenix020903** [MAVRICK-1/Nest-Ondc#36]
**Describe the bug**
The repeated use of the same card on this page, resulting in the duplication of the same product, detracts from the overall appearance.

**To Reproduce**
->Eliminate duplicate cards 
->Introduce new ones to rectify the discrepancies.

**Screenshots**
![Screenshot 2024-06-03 131353](https://github.com/MAVRICK-1/Nest-Ondc/assets/129112358/25f8499a-7a5c-4547-9b78-7d7ce5bcb078)

**Additional Content**
Please assign this issue to me under SSOC'24.

**Comment by MAVRICK-1** [comment]
@phoenix020903 they are not duplicate, the Shop name and location is different
