### ISSUE TITLE
Email verification for SignUp

### ISSUE THREAD

**Issue by rashmi3149** [MAVRICK-1/Nest-Ondc#37]
**Is your feature request related to a problem? Please describe.**

Currently, the sign-up process does not verify email addresses, allowing users to register with non-existent Gmail accounts. This leads to invalid user entries .

**Describe the solution you'd like**

Implement email verification using Firebase Authentication. Upon user registration, send a verification email. Require users to verify their email before activating their account.

**Additional context**

- Modify the sign-up logic to send a verification email.

- Restrict account activation until email verification is complete.

**Screenshots**

Even though i am using invalid gmail account

![Screenshot (4795)](https://github.com/MAVRICK-1/Nest-Ondc/assets/113359160/e348f263-525d-4d5b-9e68-bf3011ff1b30)

![Screenshot (4796)](https://github.com/MAVRICK-1/Nest-Ondc/assets/113359160/f4ececca-0b0b-4056-9712-72936359137a)

**Comment by rashmi3149** [comment]
Hi @MAVRICK-1 please assign this issue to me under SSOC'24.

**Comment by MAVRICK-1** [comment]
@rashmi3149 go-ahead
