### ISSUE TITLE
Remove "HTML Ecommerce Template" in Footer

### ISSUE THREAD

**Issue by kushagra-singhh** [MAVRICK-1/Nest-Ondc#38]
## Description : 
In the footer section of the page , it says "© 2024, Nest - HTML Ecommerce Template All rights reserved" however it should be "© 2024, Nest - All rights reserved"

## Screenshot : 
![image](https://github.com/MAVRICK-1/Nest-Ondc/assets/88451512/cf440866-f553-4aad-aa37-82f32e45af97)

**Comment by kushagra-singhh** [comment]
I would like to fix this issue. Please assign it to me under ssoc

**Comment by MAVRICK-1** [comment]
@kushagra-singhh okay go ahead
