### ISSUE TITLE
[Feature Addition] : Add Delivery Information Page as per ONDC Delivery Information.

### ISSUE THREAD

**Issue by kushagra-singhh** [MAVRICK-1/Nest-Ondc#39]
## Problem : 
The delivery information section in footer is unresponsive because there is no delivery information page. 

## Proposed Solution : 
Create a Delivery information page and link it to the button in footer of the website. The delivery information such as delivery timelines, etc. will be as per the ONDC's delivery timelines as available on its website.

## Screenshot : 
![image](https://github.com/MAVRICK-1/Nest-Ondc/assets/88451512/6b431471-bea9-4359-97bc-6746b1ba123b)

**Comment by kushagra-singhh** [comment]
I would like to work on this issue. Please assign it to me under SSOC'24

**Comment by MAVRICK-1** [comment]
@kushagra-singhh not needed
