### ISSUE TITLE
[Bug] Duplicate Entries in Footer even after patch of Issue #19

### ISSUE THREAD

**Issue by kushagra-singhh** [MAVRICK-1/Nest-Ondc#40]
## Description : 
There are duplicate entries in the footer section of the website even after the fix of https://github.com/MAVRICK-1/Nest-Ondc/issues/19 . https://github.com/MAVRICK-1/Nest-Ondc/issues/19 patch only removes the duplicate 'Company' section. But there is 'Corporate' and 'Popular' section in the footer with the same content as 'Company'

**To Reproduce**

1. Go to Home.
2. Scroll down to End.
3. See Footer.

**Screenshot :** 
![image](https://github.com/MAVRICK-1/Nest-Ondc/assets/88451512/21181aac-40b6-4da9-a687-3c89a518b423)

- OS : Windows
- Browser : Chrome

**Comment by kushagra-singhh** [comment]
pls assign this issue to me under ssoc

**Comment by MAVRICK-1** [comment]
@kushagra-singhh not needed
