### ISSUE TITLE
Unresponsive Subscribe Newsletter Button on Carousel for Smaller Screens

### ISSUE THREAD

**Issue by jeevan10017** [MAVRICK-1/Nest-Ondc#43]
I've encountered an issue while navigating through our project's website on smaller screens. It appears that the 'Subscribe' button in our newsletter carousel is not aligned. This issue has not been explicitly stated in our documentation or issue tracker for smaller screens. I have viewed in a chrome Version 125.0.6422.141 (Official Build) (64-bit)

As an **SSOC contributor**, I would like to bring this to your attention and request that this work be assigned to me so that I can investigate and resolve it promptly.

**Steps to reproduce:**
1. Reduce browser window size or view on a mobile device.
2. Navigate to the homepage carousel featuring the newsletter subscription.
![Screenshot 2024-06-04 004051](https://github.com/MAVRICK-1/Nest-Ondc/assets/132948936/72ab580f-988e-4f54-a062-8406612ba0d4)

3. Subscription button is not aligned

**Expected result:**
The button should be the same when we view it on the desktop screen.

**Actual result:**
The button remains unresponsive and not aligned with smaller screens.

I believe addressing this will significantly improve user experience, especially for those accessing our site via mobile devices.

**Comment by MAVRICK-1** [comment]
@jeevan10017 okay go ahead

**Comment by jeevan10017** [comment]
@MAVRICK-1  Can you please explain why it happened?
my whole night effort got ruined 😢

![Screenshot 2024-06-09 012810](https://github.com/MAVRICK-1/Nest-Ondc/assets/132948936/27dddf2c-59e0-4366-a7ab-ef39b1a96dcf)
