### ISSUE TITLE
Open Graph implementation for the website 

### ISSUE THREAD

**Issue by Trident09** [MAVRICK-1/Nest-Ondc#45]
### **Feature Request: Add Open Graph Support**

**Feature missing.**

Currently, links from this website don't display rich previews on social media, making shared content look unattractive.

**Describe the solution you'd like**

Add Open Graph tags to our website, including:

- `og:title`
- `og:description`
- `og:image`
- `og:url`

This will ensure our links generate engaging previews on social media.

**Alternatives considered**

Considered using Twitter Card tags, but Open Graph tags are more universally supported across various platforms.

Adding these tags will improve the appearance of our shared content.

**Comment by Trident09** [comment]
I would like to fix this issue. Please assign it to me under ssoc

**Comment by MAVRICK-1** [comment]
@Trident09 okay go ahead, will give you level after reviewing your pr
