### ISSUE TITLE
remove repeating section company

### ISSUE THREAD

**Issue by Rishikesh63** [MAVRICK-1/Nest-Ondc#51]
![Screenshot 2024-06-04 120121](https://github.com/MAVRICK-1/Nest-Ondc/assets/130288820/ed10a659-1987-460a-91bf-64b7e98c5f71)

there is two company section that will not give best use experience 

by removing one section we can solve this issue

**Comment by kushagra-singhh** [comment]
Already fixed in https://github.com/MAVRICK-1/Nest-Ondc/issues/19
