### ISSUE TITLE
Adding products in daily best sales section.

### ISSUE THREAD

**Issue by happyrao78** [MAVRICK-1/Nest-Ondc#54]
Hi, I'm a SSOC contributor and i would like to add products in daily best sales section in replacement of loading.
![Screenshot 2024-06-04 133128](https://github.com/MAVRICK-1/Nest-Ondc/assets/138770813/78d097fb-ddc9-4d5a-87b5-bb112cba935d)

**Comment by MAVRICK-1** [comment]
@happyrao78 how do you planning to do that?

**Comment by happyrao78** [comment]
> @happyrao78 how do you planning to do that?

Placing the relevant images in place off loading in form of cards.

**Comment by MAVRICK-1** [comment]
@happyrao78 you have give the location access for it . Because it sort products according to location
