### ISSUE TITLE
Multiple contact number in the footer

### ISSUE THREAD

**Issue by tusharshah21** [MAVRICK-1/Nest-Ondc#55]
**Describe the bug**
the footer section contains multiple contact details of same number either it could be updated with another number or we should remove any one from the footer!

**To Reproduce**
Either remove it or change either one of the one

**Expected behavior**

**Screenshots**
![image](https://github.com/MAVRICK-1/Nest-Ondc/assets/96661387/2b784bf6-f523-4514-9286-5980fd1dc680)

**Comment by kushagra-singhh** [comment]
duplicate of #50

**Comment by tusharshah21** [comment]
my bad.! please close this issue!
