### ISSUE TITLE
wrong discount percentage

### ISSUE THREAD

**Issue by Trident09** [MAVRICK-1/Nest-Ondc#56]
**Describe the bug**
The discount percentage mentioned on products is not correct. It should be calculated by checking the original price and the current price of the product.

**Expected behavior :**
The discount percentage mentioned should be correct

**Screenshots :**
![image](https://github.com/MAVRICK-1/Nest-Ondc/assets/98939183/f7854f98-df4b-49f6-8c5b-93badb4d764a)
![image](https://github.com/MAVRICK-1/Nest-Ondc/assets/98939183/c4dbbbe9-0df1-46b9-90a8-1c718cd013f4)

**Comment by Trident09** [comment]
pls assign this issue to me under ssoc.

**Comment by MAVRICK-1** [comment]
@Trident09 okay go ahead
