### ISSUE TITLE
Product Images Not Loading Due to API Call Failure – Shows 'Loading...' Text Instead

### ISSUE THREAD

**Issue by ShikharSinghKushwaha** [MAVRICK-1/Nest-Ondc#57]
Whenever the application is Loading or Navigating to different Porduct Categories the image is not loading as expected Instead the text show like 'Loading..'.

**To Reproduce**
This could be due to api call Failure or not properly handling the nested  array-objects to list all the information about the product .

**Screenshots**
![Screenshot (45)](https://github.com/MAVRICK-1/Nest-Ondc/assets/100946083/3c05e233-e72b-4fc5-b293-0941ec27b2ed)

Assign me this issues to Start working on it .  ssoccontributor

**Comment by MAVRICK-1** [comment]
@ShikharSinghKushwaha you need to give location access for that , because our app uses openstreet map to sort the nearest item according to your location.

**Comment by ShikharSinghKushwaha** [comment]
@MAVRICK-1  Oh... okay got it ..
