### ISSUE TITLE
Add a terms & conditions page.

### ISSUE THREAD

**Issue by kushagra-singhh** [MAVRICK-1/Nest-Ondc#61]
**Is your feature request related to a problem? Please describe.**
There exists no terms and conditions page.

**Describe the solution you'd like**
I will add a tnc page which will follow the design laguage of the website.

**Additional context**
I will create the paga and link it to the terms and conditions section at the footer of website.

**Comment by kushagra-singhh** [comment]
I am working on this issue. Please assign it to me!

**Comment by iamrudhresh** [comment]
I hope you're doing great! As a SSOC contributor, I'm keen on ramping up my involvement for SSOC'24. Could you please assign this issue to me? I'm excited to continue contributing to the project. Thanks a bunch!

**Comment by MAVRICK-1** [comment]
@kushagra-singhh go ahead , will mark you level after seeing your pr
