### ISSUE TITLE
Address in the footer is not appropriate

### ISSUE THREAD

**Issue by aapJoysakoi** [MAVRICK-1/Nest-Ondc#63]
**Describe the bug**
The address in the footer is an US address. Since it is an Indian website, address should be Indian as well.

**Screenshot**
![image](https://github.com/MAVRICK-1/Nest-Ondc/assets/114143879/52cdb724-bb01-4409-8563-6788969dc906)

**Comment by aapJoysakoi** [comment]
please assign me this issue under SSOC.

**Comment by MAVRICK-1** [comment]
@aapJoysakoi okay go ahead , pic my address , "kopidanga , chinsurah , hooghly , west bengal , india"
