### ISSUE TITLE
Email Validation on home page banner and above footer. 

### ISSUE THREAD

**Issue by aapJoysakoi** [MAVRICK-1/Nest-Ondc#64]
**Is your feature request related to a problem? Please describe.**
yes. The newsletter input option on home page banner and above footer for entering the email I'd accepts any string of text.

**Describe the solution you'd like**
 I intend to change it to accept only valid email I'd(s). 

**screenshots**
![image](https://github.com/MAVRICK-1/Nest-Ondc/assets/114143879/d6510b81-cd41-42a1-af17-308dd972e130)
![image](https://github.com/MAVRICK-1/Nest-Ondc/assets/114143879/a27ed703-174b-4877-baf6-bd9668b2949a)

**Comment by aapJoysakoi** [comment]
please assign me this feature under SSOC.

**Comment by MAVRICK-1** [comment]
@aapJoysakoi this is not that needed , but anyways go ahead
