### ISSUE TITLE
"My Wishlist" Coming Under profile icon is not redirecting to Wishlist Page

### ISSUE THREAD

**Issue by aditya-chari25** [MAVRICK-1/Nest-Ondc#73]
**Describe the bug**
Under the Profile Icon the My Wishlist Button is not linking to the Wishlist Page Present

**To Reproduce**

1. Go to Profile Icon on top right corner after logging in and click on it
2. Go down to the third bar "My Wishlist Icon" and select it.
3. Not redirecting to the "My Wishlist" Page"

**Expected behavior**
It has to redirect to the "My Wishlist Page" but isn't doing it

**Screenshots**

![bug](https://github.com/MAVRICK-1/Nest-Ondc/assets/84094715/10c1a2d1-91d6-4641-a0a2-501b3f61ac95)

**Comment by aditya-chari25** [comment]
Please assign the above issue to me.

**Comment by aditya-chari25** [comment]
> Please assign the above issue to me.

@MAVRICK-1 under SSOC'24

**Comment by MAVRICK-1** [comment]
@aditya-chari25 go ahead

**Comment by aditya-chari25** [comment]
@MAVRICK-1 please check this pull request related to this issue https://github.com/MAVRICK-1/Nest-Ondc/pull/94 .

**Comment by aditya-chari25** [comment]
Issue closed with pr https://github.com/MAVRICK-1/Nest-Ondc/pull/94
