### ISSUE TITLE
Selection in Related Product doesn't redirect to that page

### ISSUE THREAD

**Issue by aditya-chari25** [MAVRICK-1/Nest-Ondc#76]
**Describe the bug**
Under the Related Products , Selection of the Product changes only the url but the product is yet the same,

**To Reproduce**

1. Go to the website and select any product.
2. Scroll down and under related products select any product.
3. You can see only the url is changing not the Product.

**Expected behavior**
The product shown also change accordingly but it is not happening and must be changed.

**Screenshots**
As we select the Tata Sappan Product (Product/4) the above url is changing but not the product (it's still
showing Good life product which is Product/3 ) and this has to be changed.

![bug2](https://github.com/MAVRICK-1/Nest-Ondc/assets/84094715/e86ed86f-b88d-44c0-8d4c-0becc28299b7)

@MAVRICK-1 Please assign this issue to me.

**Comment by MAVRICK-1** [comment]
@aditya-chari25 go ahead
