### ISSUE TITLE
Sign in and Forgot Password Feature not working

### ISSUE THREAD

**Issue by rashmi3149** [MAVRICK-1/Nest-Ondc#8]
**Describe the bug**
Sign in button not working in mobile device. And forgot password button shows 404 status code when clicked. 

**Expected behavior**
- The 'Sign In' button should function properly and allow users to sign in.
- The 'Forgot Password' button should redirect users to a password recovery page instead of showing a 404 error.

**Screenshots**
![Screenshot 2024-05-30 075703](https://github.com/MAVRICK-1/Nest-Ondc/assets/113359160/99de5abb-4b72-42ab-9aaa-7e153640e158)
![sign in](https://github.com/MAVRICK-1/Nest-Ondc/assets/113359160/49b329a1-4610-4992-8cd8-06b0dc8616ee)

**Desktop :**
- OS: [Windows 11 Pro]
- Browser [chrome]
- Version [125.0.6422.113]

**Smartphone:**
- Device: [Realme 8 Pro]
- OS: [Android Version 13]
- Browser [chrome]
- Version [125.0.6422.112]

**Comment by rashmi3149** [comment]
I have read the contributing guidelines and code of conduct. @MAVRICK-1 please assign this issue to me under label SSOC'24 . Thank You

**Comment by MAVRICK-1** [comment]
Okay go ahead create a forget password, and  also add the forget password firebase functionality

**Comment by MAVRICK-1** [comment]
Css class should be in hierarchical structure

**Comment by rashmi3149** [comment]
Hi @MAVRICK-1 ,please review my PR.
