### ISSUE TITLE
Add Contact Us page

### ISSUE THREAD

**Issue by ShreeluSantosh** [MAVRICK-1/Nest-Ondc#83]
## Is your feature request related to a problem? Please describe.
In the footer, as well as navbar, the Contact does not lead to the Contact Us page. On examining the repo, it appears that Contact page is missing from `pages` directory

## Screenshot
![image](https://github.com/MAVRICK-1/Nest-Ondc/assets/94289402/57d067d9-0680-43da-9f1c-eef16a38cb62)
The current Contact button just redirects us to the current page, as evident from the URL in bottom left corner of the screen

## Describe the solution you'd like
* Create a Contact Us page with same styling as other pages
* Add the following sections to the Contact Page:
1. Contact Information
2. FAQ section (with toggle)
3. Customer service hours (should be clearly displayed)
4. Contact Form
5. Include link to Privacy Policy
6. Include social media links

## Additional context
Assign me this issue under GSSOC'24 (gssoc label)

**Comment by ipsita5-dut** [comment]
![Screenshot 2024-06-08 101738](https://github.com/MAVRICK-1/Nest-Ondc/assets/157873351/5c1f0870-52fc-4136-99a1-a88b4ff228a1)
This is the sample that I want to change in this project.
Hello , I want to contribute in this project. As per your description of the solution you want , I can add the contact us page for this.
In that I will first add the contact information that you want and then by using CSS I can add a portion for adding social media links that will change colors when hovered. Also by adding url for google maps the address can be shown in the map as well as by text. Then before the contact information there will be an FAQ section with toggling option. I hope I will be able to fulfil your request, 
Please accept my request and assign me for contribution under GSSOC'24.

**Comment by MAVRICK-1** [comment]
@ShreeluSantosh go ahead

**Comment by Palakmeena** [comment]
Please assign this issue to me

**Comment by ShreeluSantosh** [comment]
Linked PR: #99
