### ISSUE TITLE
Adding a colour when we hover in navbar on groceries to make it more attractive  @ssoc

### ISSUE THREAD

**Issue by Krishna100604** [MAVRICK-1/Nest-Ondc#84]
when we hover on item it should be highlighted with  website's default colour (light green)

![Screenshot (110)](https://github.com/MAVRICK-1/Nest-Ondc/assets/110299021/1b32e32d-da17-42ce-a7c9-a16432703a88)

@MAVRICK-1 please assign me this

**Comment by AnClicks** [comment]
@Krishna100604 are you taking about all the elements of the page?

**Comment by Krishna100604** [comment]
@AnClicks > @Krishna100604 are you taking about all the elements of the page?

no ,i have attached the image above you can see in that  i am talking about sub items in groceries ,electronics

**Comment by Krishna100604** [comment]
@MAVRICK-1     I committed the changes please accept my pull request

**Comment by Palakmeena** [comment]
Please assign this issue to me

**Comment by Krishna100604** [comment]
@Palakmeena  It has already been assigned to me
