### ISSUE TITLE
Zoom option present in map 

### ISSUE THREAD

**Issue by Aryan741x** [MAVRICK-1/Nest-Ondc#85]
**Zoom buttons overlapping the content of the Page**
While Scrolling the Page i have noticed that the zoom button was overlapping the contents present in the page(Cart) .I think this should not happens .Kindy assign this issue to me under SSOC 24 . I would do my best to solve this problem .

**To Reproduce**
Go to the Any Page containing the Map . Scroll down the Page you will notice that the zoom button present on the page provided by google map is overlapping the contents of the page 

**
**Screenshots**
![Screenshot 2024-06-07 173228](https://github.com/MAVRICK-1/Nest-Ondc/assets/128162387/a0921eef-0fff-468c-a1d7-3650180d6f06)

**Additional context**
Also in Screenshot i have observed that the cart box is not fixed it moves relative to the page until below banner do not show up . If this is a issue kindly let me know i will create a new issue for that too.

**Comment by MAVRICK-1** [comment]
@Aryan741x current we are using react leaflet library for the map , and zoom button is including in it.
