### ISSUE TITLE
Layout Rendering Issue in Firefox.

### ISSUE THREAD

**Issue by Himani2615** [MAVRICK-1/Nest-Ondc#92]
**Describe the bug**
Elements appear to be misaligned, and some styles are not applied as expected. This is causing the page to look broken and affects the user experience negatively.

**To Reproduce**

1.Open the website in Firefox.
2.Navigate to the home page.
3.Observe the layout and styles.

**Expected behavior**
The elements should be aligned correctly, and all styles should be applied as defined in the CSS.

**Screenshots**
![Screenshot (230)](https://github.com/MAVRICK-1/Nest-Ondc/assets/143219485/b78f07ab-a731-4bb4-97b4-7d74b9ca1771)

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Firefox
- Version: 126.0.1 (64-bit)

  Please assign this issue to me, I would like to work on it.

**Comment by MAVRICK-1** [comment]
@Himani2615 go ahead

**Comment by akbatra567** [comment]
PR is already merged. Closing the issue.
